apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-helm
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: jenkins
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://lukyanchyk.github.io/helm-14hw/
    targetRevision: 0.1.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
