apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: repo-855896192
  namespace: argocd
spec:
  encryptedData:
    project: AgDheYykV/spQTqOzS7MMq83NomrlDhkrymBpmLSXdJ8JiUEBYDfaNhhLLRDSJkZOVUufhRmtDeup1L2J1uxpteYF2Ibj7lWH8UcQ5kP1FdMSN96i6+IBYawOL51cTUvTAJgYtByqXtrDkuAXaiDSRROFM2CzIslCo1Y/qpbk4TwHdthr70EyOeT0Vt9y89NRsbaRdGXeJHySrDZSegBSkZeToNSt3QtQKrGn8V2lZXVotvkwVeNXcix0J5MTePnQ+sGwYQrG8CphZ6PVcqdFk1lfmFJpV6FxeNybcR2o2Jtym1HX/q7SQXWY8ABWhuMUAmJGA54Ij9HsmKjlf/EE+NCL5LFAaTHrrC5lDj4TNZsTupa6WCbH7DeWhp+JEdycq851XlJW1LtF8w1mli6GaiZe9nX/G2lOXXp0MNoHl0DUVz+kTTbCYJXK/tkfl6p5CwdmJdgrra6CWV0BzEzacejnlvSndJpULlTUWYPrKm5BCNIUlFNCBNpgrGMZ/hFBa9nyVzWPQ0Hh3BC2YZI9qUFNLAGkxYPAu8unGE7+L547/aahq0F9ZVD1jVgfeF3aQOyEHfXULmVDPD2LcMCiroZVu1x3zf0DY2ZtjIjs86OUi0+It0Z40HHJofQ7Eg7UeBDP102q6gXqDUxSZgUMgLMB6XQB5ia6h5+WwVMM3UtypGNM3UxmeoD3Es8GBE8jeG9pFnOfSO8
    type: AgCJGw8Rj3kmmDnXtfUoE4K308y9a5P0Lifwu0O/cGQ1kDdaLpkIM4zPXmMVUD5dJKXZg39f18L9IFa6wOh5ckIV9lZW0dBvvqTAzAK2PQjW0Lb2exZUBDIUvhULzFuh3oCTk+sk1SKfymm/9XaIt15qx6uqMMJg/KRxkJkTULb0dGIADAkDy1pgG0MH8uXdJzntTjCVj4aKRRnfKu1leg8DhIQN25ASc+10DMH9yjOx+2hlOGci+3QnTYlaFOrc9jcy8r+aWfXFrktNvLn5LsjlK5gLILyY8l8DC1RIzxM/7OO+f93V6urrey5LqMtXG92lgQiprLf4McY/SaTFXJoHa/MYTRuEYCPNizDxJVGLUuZrLym+Na5YItnWcl0JBwjWdfmXcv7p3wUdriD/7/a1GdY9MBwf78VxOG9GlK4bh/8HxZHGeb2cW5m9XX58iu2RCh3mmSPF8DvteFcmv8lAhzpxaTm65/1OOKE92uI9i2/mKW9VkaCewXJjVDVggXpTxIK64XUb17VLRaD/AGZT5jzW3oqNeDtMcyQXNFlItnzlvpl1GFsSLTnJRAVB6N7THpKiOgZ87l7f0w+Sb0sHUIXUOSTLFdmVWRKO0kXcQKhuTEZQHsQnWUmTAihldc06F83pktAi9kQhP0TjXB1w2+5X4HPoyrFEQouT1/BvqsYH6yfvCmTsH/VCQVDcC3dKYDo=
    url: AgCDqVQXBlNKYTdrDtpbITqEj0dYlkAYu1rRdWgcHQ5GMaIx/gvxaPfPuKCOaDOtRw36ZJwGGv8C41QmR7emG8USibdHr3nMtVXODyxtcJYeRQDPtoSKW3SMWbjqoLRNP3y90aWYCV/dJ3fYsdLzsR45E9H3uaw21CI1wNtN2d3zwx7Cx5GANeNl72yEglcoCbOwe9ECJbtKR6l6odOUtTLzSDvVExo3L3ZyAwuw5zY27FZ1ZaNpTR8cJACei++tYqbXQqKqgJ1xoYM0+zuqY23RqHIZ6QwfphpyXYXZU99D5Tdri0W/K11ZvG4E9Of7xYF57Vgogswcwnmm2/CDJhinQXYz5u4vkMjcvTN8Cwx/kz9uuWabWwNxZcVSd3tytT2ngZryTkABpRdvwSop+NhVToD9Tts6wqR3FDD3kGtxZVVVj1I3v5sf+55jkPS7a7BEU1jHiTPg6cN2cpnlwWypaMJgM3gjrDWZuG/LEJ9kRMr1qSUebkdbvlChbXh1EdUHxd43nnY1zaFUCfh0iLZYnLzAYrQqszEyJeSuR95+Ek1EmH4qZWC07Uejo+CoiYuwE4q+Gq88yfsBBPms9ePGVqlKeZo+BPLgef4qK11T4y5ts8MFGPsXrUF0VqyXPZ8YFCAgnnx+j/ndOshjmo5dEdLZzcpWtloWPe2yzf5rF1J2t7Z6+ZCdw1tISLRSFglBTBwEuNhEKYdbagdHsG/OfBy1Ij7v/JSGqGLgONrtwvIZ
  template:
    metadata:
      annotations:
        managed-by: argocd.argoproj.io
      creationTimestamp: null
      labels:
        argocd.argoproj.io/secret-type: repository
      name: repo-855896192
      namespace: argocd
    type: Opaque

